language: perl
perl:
    - '5.20'
    - '5.18'
    - '5.16'
    - '5.14'
    - '5.12'
install: cpanm -n
    HTTP::Tiny
    JSON::MaybeXS
    Moo
    Test::Fatal
    Test::MockObject
    Test::More
    URI
script: prove -lv
