language: perl
perl:
    - '5.20'
    - '5.18'
    - '5.16'
    - '5.14'
install: cpanm -n --skip-satisfied
    JSON::PP
    Test::Fatal
    Test::MockObject
    URI::Query::FromHash
script: prove -lv
sudo: false
