name: Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        include:
          - cover: true
            perl: '5.32'
        perl:
          - '5.20'
          - '5.22'
          - '5.24'
          - '5.26'
          - '5.28'
          - '5.30'

    runs-on: ubuntu-latest

    name: ${{ matrix.perl }}

    steps:
      - uses: actions/checkout@v2

      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}

      - run: perl -v

      - run: cpanm -n Test2::V0 URI::Query::FromHash

      - if: ${{ !matrix.cover }}
        run: prove -lv

      - if: ${{ matrix.cover }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cpanm -n Devel::Cover::Report::Coveralls
          PERL5OPT=-MDevel::Cover prove -lv
          cover -report coveralls
